require 'tetris/add_block'
require 'tetris/anchor_block'
require 'tetris/block_definitions'
require 'tetris/board'
require 'tetris/decompose_block'
require 'tetris/move_block'
require 'tetris/random'
require 'tetris/row_removal'
require 'tetris/tick_tock'

require 'tetris/helper_methods'
